### PR TITLE
Add Python (3!) support.

### PR DESCRIPTION
**Pull request by chadmiller**

### CODE REVIEW

**Comment by mlaco** [comment]
I'll probably pull this, but I wanted to make sure you realized something first, and then see if you still want me to pull.
The function of my gem is not the methods which return numbers from method names. For that, I used the gem [numbers_in_words](https://github.com/markburns/numbers_in_words). My gem takes that and defines method on the array class specifically. Your code is more similar to numbers_in_words.
If you realize that (and I've insulted your intelligence), and you still want me to pull, just say the word ;)

**Comment by chadmiller** [comment]
Thanks. I considered that but I didn't do it because 

1) ) there are several kinds of iterables in Python. not just Array. We rely on the standard syntax to work the right way, whether it's on a List, Tuple, database object mapping, or whatever.  Changing one and not others would be too weird. Changing them all is impossible. You or any module can define your own.

And, 2) it's darned hard to change it so slicing an iterable would return an object that also supports that functionality. In Python, patching things is not a virtue.

**Comment by mlaco** [comment]
@chadmiller Thanks for the explanation. That makes sense. I'm wondering, is it common to add Python support on a Ruby gem?

**Comment by chadmiller** [comment]
I don't know. I have never looked at a Ruby gem before. I suspect not,
because that would be audacious and silly.

**Comment by mlaco** [comment]
Well we did it anyway!!!

**Pull request merged**
